# Generated by Django 5.1.6 on 2025-02-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vehicletransportrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletransportrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vehicletransportrequest',
            name='last_name',
        ),
    ]
